# Generated by Django 3.1.5 on 2021-01-13 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(blank=True, max_length=22, null=True, verbose_name='实例ID')),
                ('instance_name', models.CharField(max_length=22, verbose_name='显示名称')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='实例的描述')),
                ('image_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='镜像ID')),
                ('region_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='实例所属地域ID')),
                ('zone_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='实例所属可用区')),
                ('cpu', models.IntegerField(verbose_name='CPU核数')),
                ('memory', models.IntegerField(verbose_name='内存大小，单位: GB')),
                ('instance_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='实例资源规格')),
                ('status', models.CharField(choices=[('Running', '运行中'), ('Starting', '启动中'), ('Stopping', '停止中'), ('Stopped', '已停止')], default='Running', max_length=8, verbose_name='主机状态')),
                ('hostname', models.CharField(blank=True, max_length=23, null=True, verbose_name='主机名称')),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP')),
                ('private_ip', models.GenericIPAddressField(verbose_name='私网IP')),
                ('os_type', models.CharField(default='linux', max_length=10, verbose_name='操作系统类型')),
                ('os_name', models.CharField(default='', max_length=20, verbose_name='操作系统名称')),
                ('instance_charge_type', models.CharField(choices=[('PrePaid', '预付费'), ('PostPaid', '后付费'), ('local', '本地购买')], default='PrePaid', max_length=8, verbose_name='付费方式')),
                ('creation_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('expired_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'permissions': (('view_host', '查看主机信息'), ('add_host', '添加主机信息'), ('change_host', '更新主机信息'), ('delete_host', '删除主机信息')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Kubernetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Deployment', '无状态'), ('StatefulSet', '有状态'), ('DaemonSet', '守护进程集'), ('Job', '任务'), ('CronJob', '定时任务')], default='Deployment', max_length=32, verbose_name='种类')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('namespace', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('limits_cpu', models.IntegerField(verbose_name='最小CPU核数-Core')),
                ('limits_memory', models.IntegerField(verbose_name='最小内存-M')),
                ('requests_cpu', models.IntegerField(verbose_name='最大CPU核数-Core')),
                ('requests_memory', models.IntegerField(verbose_name='最大内存-M')),
                ('gitlab', models.CharField(blank=True, max_length=32, null=True, verbose_name='对应的GIT仓库')),
                ('tags', models.CharField(blank=True, max_length=32, null=True, verbose_name='GITLAB中最后的标签')),
            ],
            options={
                'verbose_name': '主机用户名',
                'verbose_name_plural': '主机用户名',
                'permissions': (('view_Kubernetes', '查看息K8S的部署信'), ('add_Kubernetes', '添加K8S的部署信息'), ('change_Kubernetes', '更新K8S的部署信息'), ('delete_Kubernetes', '删除K8S的部署信息')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Paas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='平台名称')),
            ],
            options={
                'verbose_name': '运维平台',
                'verbose_name_plural': '运维平台',
                'permissions': (('view_paas', '查看运维平台'), ('add_paas', '添加运维平台'), ('change_paas', '编辑运维平台'), ('delete_paas', '删除运维平台')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='项目组名称')),
                ('name_cn', models.CharField(max_length=32, verbose_name='项目组中文名称')),
            ],
            options={
                'verbose_name': '项目组',
                'verbose_name_plural': '项目组',
                'permissions': (('view_project_group', '查看项目组'), ('add_project_group', '添加项目组'), ('change_project_group', '编辑项目组'), ('delete_project_group', '删除项目组')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('name_cn', models.CharField(max_length=100, verbose_name='中文名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签类型',
                'verbose_name_plural': '标签类型',
                'permissions': (('view_type', '查看标签类型'), ('add_type', '添加标签类型'), ('change_type', '编辑标签类型'), ('delete_type', '删除标签类型')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('name_cn', models.CharField(max_length=100, verbose_name='中文名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.type', verbose_name='类型')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'permissions': (('view_tag', '查看标签'), ('add_tag', '添加标签'), ('change_tag', '编辑标签'), ('delete_tag', '删除标签')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='中文名称')),
                ('region', models.CharField(max_length=32, verbose_name='代码名称')),
                ('endpoint', models.CharField(max_length=32, verbose_name='连接')),
                ('paas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.paas', verbose_name='平台名称')),
            ],
            options={
                'verbose_name': '云平台区域',
                'verbose_name_plural': '云平台区域',
                'permissions': (('view_region', '查看云平台区域'), ('add_region', '添加云平台区域'), ('change_region', '编辑云平台区域'), ('delete_region', '删除云平台区域')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HostUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.host', verbose_name='主机')),
            ],
            options={
                'verbose_name': '主机用户名',
                'verbose_name_plural': '主机用户名',
                'permissions': (('view_host_username', '查看主机用户名'), ('add_host_username', '添加主机用户名'), ('change_host_username', '更新主机用户名'), ('delete_host_username', '删除主机用户名')),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='host',
            name='paas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.paas', verbose_name='所属平台'),
        ),
        migrations.AddField(
            model_name='host',
            name='project_group',
            field=models.ManyToManyField(blank=True, to='cmdb.ProjectGroup', verbose_name='所属项目组'),
        ),
        migrations.AddField(
            model_name='host',
            name='tags',
            field=models.ManyToManyField(blank=True, to='cmdb.Tag', verbose_name='标签'),
        ),
    ]
