# Generated by Django 3.1.5 on 2021-01-13 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectgroup',
            name='userinfo',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='项目组成员'),
        ),
        migrations.AlterField(
            model_name='host',
            name='project_group',
            field=models.ManyToManyField(blank=True, null=True, to='cmdb.ProjectGroup', verbose_name='所属项目组'),
        ),
    ]
