# Generated by Django 3.1.5 on 2021-01-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210113_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetes',
            name='paas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.paas', verbose_name='所属平台'),
        ),
        migrations.AddField(
            model_name='kubernetes',
            name='project_group',
            field=models.ManyToManyField(blank=True, null=True, to='cmdb.ProjectGroup', verbose_name='所属项目组'),
        ),
    ]
