# Generated by Django 3.1.5 on 2021-01-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20210114_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostusername',
            options={'default_permissions': (), 'permissions': (('view_host_username', '查看主机用户名'), ('add_host_username', '添加主机用户名'), ('change_host_username', '更新主机用户名'), ('delete_host_username', '删除主机用户名'), ('view_host_password', '查看主机密码')), 'verbose_name': '主机用户名', 'verbose_name_plural': '主机用户名'},
        ),
    ]
