# Generated by Django 3.1.5 on 2021-01-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20210114_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetes',
            name='namespace',
            field=models.CharField(max_length=32, unique=True, verbose_name='命名空间'),
        ),
    ]
