# Generated by Django 3.1.5 on 2021-01-15 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0006_auto_20210115_1428'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='任务名')),
                ('content', models.TextField(help_text='永远只保存最新内容', null=True, verbose_name='更新内容')),
                ('status', models.IntegerField(choices=[(-1, '已取消'), (0, '待审核'), (1, '未通过'), (2, '待发布'), (3, '已发布')], default=0)),
                ('review_at', models.DateTimeField(null=True, verbose_name='审核时间')),
                ('review_notes', models.CharField(max_length=255, null=True, verbose_name='审核意见')),
                ('publish_at', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('result', models.TextField(null=True, verbose_name='执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('dest_hosts', models.ManyToManyField(related_name='host_tasks', to='cmdb.Host', verbose_name='目标主机')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '任务系统',
                'verbose_name_plural': '任务系统',
                'permissions': (('view_task', '查看任务'), ('add_task', '添加任务'), ('change_task', '编辑任务'), ('delete_task', '删除任务'), ('review_task', '审核任务'), ('publish_task', '发布任务'), ('view_history', '查看历史')),
                'default_permissions': (),
            },
        ),
    ]
